name: Fetch Sub Claims
'on': push

jobs:
  fetch_sub_claims:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
steps:
      - name: Fetch Sub Claims from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-sub-claims
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-type: jwt
        run: |
           # Use the secret securely within this step
           echo "Doing something with ${{ secrets.AKEYLESS_ACCESS_ID }}
           curl --request POST --url https://api.akeyless.io/describe-sub-claims  --header 'accept: application/json' --header 'content-type: application/json' --data '{"json":false}'
          

