name: Fetch Static Secrets example

'on': push

jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Fetch static secrets from Akeyless
      uses: akeyless-community/akeyless-github-action@v1.0.1
      id: fetch-secrets
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        static-secrets: |
          - name: "/github-secret-01"
            output-name: "secret-from-thales"
        api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2/"
   
    - name: Fetch SubClaim
      run: |
        # Use the secret securely within this step
        curl --request POST --url https://api.akeyless.io/describe-sub-claims  --header 'accept: application/json' --header 'content-type: application/json' --data '{"json":false}'
        
