name: Fetch Sub Claims

'on': push

jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Fetch Sub Claims from Akeyless
      uses: akeyless-community/akeyless-github-action@v1.0.1
      id: fetch-secrets
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
            
    - name: Check Sub Claims
      run: |
            echo  ${{ secrets.ACCESS_ID }} 


     

     
